[config]
default_to_workspace = false

#---------------------------------------
# Development tasks
#---------------------------------------

#
# Define `$ cargo make paclet-install`
#
[tasks.paclet-install]
dependencies = ["paclet"]
command = "wolfram-cli"
# TODO: Fix this hard-coded version number.
args = ["paclet", "install", "build/ConnorGray__NotebookWebsiteTools-0.0.1.paclet"]

#
# Define `$ cargo make paclet`
#
[tasks.paclet]
dependencies = []
command = "wolfram-cli"
args = ["paclet", "build", "./paclets/NotebookWebsiteTools", "./build"]